name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v4
    - run: cargo test --workspace

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v4
    - run: cargo fmt -- --check
